### PR TITLE
DEVOPS-689 Testing bors

### PR DESCRIPTION
**Pull request by jorge-cr-13**
## What 🕵️ 🔍

- Testing the bors functionality for the repository.

## References 📝 🔗

- [Jira task](https://xainag.atlassian.net/jira/software/projects/DEVOPS/boards/65?selectedIssue=DEVOPS-689)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Update(s) to the configuration of existing service(s)
- [ ] This change requires a documentation update
- [ ] Removed some deprecated application or functionality

## Reviewer checklist

*Reviewer agreement:*

* Reviewers shouldn't review a "Draft Pull Request", but rather wait for it to be marked as "Ready for Review".
* Reviewers do **not** commit or merge the pull request.
* If/when there are changes that need to be applied (applying Terraform or deploying Kubernetes manifests), the **assignee** is the one responsible for doing it.
* Use the labels `not-applied`, `partially-applied` and `fully-applied` so others know the current progress.
  * Remember to change labels accordingly once you start and finish to apply the changes.

## Checklist:

- [x] I have made corresponding changes to the documentation.
- [x] I have performed a self-review of my own code.
- [x] I did not commit anything sensitive like keys or secrets.
- [x] I added the corresponding labels.
- [x] I set the reviewers and the assignees.
- [ ] All open comments and discussions have been resolved.
- [x] My branch is following the name pattern: `JIRA-ID_Short_descripton`, example: `DEVOPS-000_some_meaningful_description`

### CODE REVIEW

**Comment by jorge-cr-13** [comment]
bors merge

**Comment by jorge-cr-13** [comment]
bors merge

**Review by abargiela — APPROVED** [review]

**Comment by abargiela** [comment]
bors help

**Comment by abargiela** [comment]
bors ping

**Comment by jorge-cr-13** [comment]
bors ping

**Comment by abargiela** [comment]
bors ping

**Pull request merged**
